### ISSUE TITLE
Breaking change on minor update

### ISSUE THREAD

**Issue by Adrion** [initbizlab/oc-cumuluscore-plugin#20]
As user may use automatic deployments with oc-boostraper please avoid minor version bump for breaking change. 

3 breaking change in few updates is a lot.  It becomes hard to maintain your plugin in a website. 😕 

Just a notice, you can close it as you read it 😄 
Many thanks for your work 👍

**Comment by czerwonyd** [comment]
Hah, yep. You are absolutely right. There should not be so much of them. But what can I do if those updates may corrupt your application? I just want to inform administrators and developers that there is something they must do to proceed because automatic update can crash app.

Or maybe there should be less updates with more features included? What do you think about it?

**Comment by Adrion** [comment]
In my case I made 3 plugins that extends Cumuluscore so yes it's pretty sensitive ^^
It's ok to make regular updates and patches of course ;)

For Breaking changes like 2.0.3 use a new version tag ie: 3.0.0.
Version number should indicate if it's a safe patch or update. :)

![image](https://user-images.githubusercontent.com/5418815/50221358-235fc480-0395-11e9-927a-1bb3c7878627.png)
 
In my deployment I can lock a specific tag version. 

The plugin is pretty new, so I can understand they are some structure modifications.
Keep going it a pretty good plugin 👍

**Comment by czerwonyd** [comment]
Nice, really good to know anyone uses and appreciates it :D 

I decided to add 2.0.0. as this was really big change, but as you have probably noticed I did not have any versioning policy that makes sense.

Your approach absolutely makes sense so I will try to use it from now :)
